export const investment = {
    PERSONAL_UPDATE_INFO: 'investment/info/PERSONAL_UPDATE',
    COMMUNITY_UPDATE_INFO: 'investment/info/COMMUNITY_UPDATE',
}

export const user = {
    UPDATE_INFO: 'user/info/UPDATE',
    UPDATE_ETH: 'user/eth/UPDATE',
    UPDATE_BCST: 'user/bcst/UPDATE',
    UPDATE_LANGUAGE: 'user/language/UPDATE',
}

export const saga = {
    SUBMIT_PERSONAL_INVESTMENT: 'saga/investment/SUBMIT_PERSONAL_INVESTMENT',
    WITHDRAW_PERSONAL_INVESTMENT: 'saga/investment/WITHDRAW_PERSONAL_INVESTMENT',
    SUBMIT_COMMUNITY_INVESTMENT: 'saga/investment/SUBMIT_COMMUNITY_INVESTMENT',
    WITHDRAW_COMMUNITY_INVESTMENT: 'saga/investment/WITHDRAW_COMMUNITY_INVESTMENT',
    FETCH_PERSONAL_INVESTMENT: 'saga/investment/FETCH_PERSONAL_INVESTMENT',
    FETCH_COMMUNITY_INVESTMENT: 'saga/investment/FETCH_COMMUNITY_INVESTMENT',

    UNLOCK_WALLET: 'saga/user/UNLOCK_WALLET',
    UNLOCK_WALLET_SUCCESS: 'saga/user/UNLOCK_WALLET_SUCCESS',
    LOGOUT_WALLET: 'saga/user/LOGOUT_WALLET',
}

export const common = {
    UPDATE_SENDTRANSACTION: 'common/sendTransaction/UPDATE',
    UPDATE_ALERT: 'common/alert/UPDATE',
}